/*
 *
 * MainPage constants
 *
 */

export const FETCH_AND_LOAD = 'app/MainPage/FETCH_AND_LOAD';
export const FETCH_AND_LOAD_SUCCESS = 'app/MainPage/FETCH_AND_LOAD_SUCCESS';
export const FETCH_AND_LOAD_FAIL = 'app/MainPage/FETCH_AND_LOAD_FAIL';

export const DISPLAY_DIALOG = 'app/MainPage/DISPLAY_DIALOG';
export const CLOSE_DIALOG = 'app/MainPage/CLOSE_DIALOG';
export const SUBMIT_APPLICATION_FOR_AUTO_APPROVE = 'app/MainPage/SUBMIT_APPLICATION_FOR_AUTO_APPROVE';
export const SUBMIT_APPLICATION_FOR_AUTO_APPROVE_SUCCESS = 'app/MainPage/SUBMIT_APPLICATION_FOR_AUTO_APPROVE_SUCCESS';
export const SUBMIT_APPLICATION_FOR_AUTO_APPROVE_FAIL = 'app/MainPage/SUBMIT_APPLICATION_FOR_AUTO_APPROVE_FAIL';

export const DISPLAY_NOTIFICATION = 'app/MainPage/DISPLAY_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'app/MainPage/CLOSE_NOTIFICATION';
export const IS_IT_NEEDED_TO_DISPLAY_PW_FIELD = 'app/MainPage/IS_IT_NEEDED_TO_DISPLAY_PW_FIELD';

// export const ACCOUNT_CHECKING_SUCCESS = 'app/MainPage/ACCOUNT_CHECKING_SUCCESS';
export const ACCOUNT_CHECKING_FAIL = 'app/MainPage/ACCOUNT_CHECKING_FAIL';
export const ACCOUNT_CHECKING_SUCCESS_AND_HAVE_ACCOUNT = 'app/MainPage/ACCOUNT_CHECKING_SUCCESS_AND_HAVE_ACCOUNT';
export const ACCOUNT_CHECKING_SUCCESS_AND_NO_ACCOUNT = 'app/MainPage/ACCOUNT_CHECKING_SUCCESS_AND_NO_ACCOUNT';
export const CLOSE_SNACKBAR_CONGRATS = 'app/MainPage/CLOSE_SNACKBAR_CONGRATS';
export const CLOSE_SNACKBAR_PW = 'app/MainPage/CLOSE_SNACKBAR_PW';

export const CLOSE_SNACKBAR_EMAIL = 'app/MainPage/CLOSE_SNACKBAR_EMAIL';
export const TOGGLE_SEE_PW = 'app/MainPage/TOGGLE_SEE_PW';
