/*
 *
 * MainPage constants
 *
 */

export const FETCH_AND_LOAD = 'app/MainPage/FETCH_AND_LOAD';
export const FETCH_AND_LOAD_SUCCESS = 'app/MainPage/FETCH_AND_LOAD_SUCCESS';
export const FETCH_AND_LOAD_FAIL = 'app/MainPage/FETCH_AND_LOAD_FAIL';

export const DISPLAY_DIALOG = 'app/MainPage/DISPLAY_DIALOG';
export const CLOSE_DIALOG = 'app/MainPage/CLOSE_DIALOG';
export const SUBMIT_APPLICATION_FOR_AUTO_APPROVE = 'app/MainPage/SUBMIT_APPLICATION_FOR_AUTO_APPROVE';
export const SUBMIT_APPLICATION_FOR_AUTO_APPROVE_SUCCESS = 'app/MainPage/SUBMIT_APPLICATION_FOR_AUTO_APPROVE_SUCCESS';
export const SUBMIT_APPLICATION_FOR_AUTO_APPROVE_FAIL = 'app/MainPage/SUBMIT_APPLICATION_FOR_AUTO_APPROVE_FAIL';

export const DISPLAY_NOTIFICATION = 'app/MainPage/DISPLAY_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'app/MainPage/CLOSE_NOTIFICATION';
